name: waka
description: Transport & Missions au Gabon — Application mobile Waka
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.3

  # State management
  provider: ^6.1.2

  # Stockage local (mode hors-ligne)
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0

  # Navigation
  go_router: ^13.2.0

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10

  # Géolocalisation
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Utilitaires
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
